AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A custom resource for Okta Users and Groups.
Resources:
  okta_cf_resource:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: okta.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: A custom resource for Okta Users and Groups.
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: '*'
      Environment:
        Variables:
          OKTA_URL: <enter value here>
          OKTA_TOKEN: <enter encrypted value here>